#cloud-config
users:
  - name: mainuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - ${ssh_public_key}
runcmd:
  - sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - rm -rf /etc/ssh/sshd_config.d/*
  - curl -fsSL https://get.docker.com | sh
  - DEBIAN_FRONTEND=noninteractive apt install docker-compose -y
  - systemctl restart sshd
  - systemctl restart ssh
  - echo 'flag' > /tmp/flag