events {}

http {
    server {
        listen 80;
        listen [::]:80;

        server_name example.org www.example.org;
        server_tokens off;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$DOMAIN$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name $DOMAIN;

        ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

        # Bloquea acceso por IP directa
        if ($host ~* ^\d+\.\d+\.\d+\.\d+$) {
            return 444;
        }

        location /app1/ {
            proxy_pass http://holaweb:8080/;
        }
    }
}
