version: '3.8'

services:
  certbot:
    image: certbot/certbot
    ports:
      - "80:80"
    volumes:
      - certs:/etc/letsencrypt
      - ./init.sh:/init.sh
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:
      - internal

volumes:
  certs:

networks:
  internal:
    external: true
    name: internal
