version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.template.conf:ro
      - ./nginx/nginx.template.initial.conf:/etc/nginx/nginx.template.initial.conf:ro
    environment:
      - DOMAIN=${DOMAIN}
    entrypoint: >
      sh -c "
        echo 'Checking certificate...';
        if [ ! -f /etc/letsencrypt/live/$$DOMAIN/privkey.pem ]; then
          echo 'Non existing certificate.';
          envsubst '$$DOMAIN $$EMAIL' < /etc/nginx/nginx.template.initial.conf > /etc/nginx/nginx.conf && 
          cat /etc/nginx/nginx.conf && 
          nginx -g 'daemon off;';
        else
          echo 'Existing certificate.';
          envsubst '$$DOMAIN $$EMAIL' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && 
          cat /etc/nginx/nginx.conf && 
          nginx -g 'daemon off;';
        fi
      "
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
