events {}

http {
    server {
        listen 443 ssl;
        server_name $DOMAIN;

        ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

        # Bloquea acceso por IP directa
        if ($host ~* ^\d+\.\d+\.\d+\.\d+$) {
            return 444;
        }

        location /app1/ {
            proxy_pass http://host.docker.internal:8080/;
        }

        location /app2/ {
            proxy_pass http://host.docker.internal:9090/;
        }
    }
}
